# Generated by Django 4.2.1 on 2023-05-15 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RECICLAQUIapp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criacao", models.DateTimeField(auto_created=True)),
                ("atualizacao", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("título", models.CharField(max_length=255)),
                ("url", models.URLField(unique=True)),
            ],
            options={
                "verbose_name": "RECICLAQUI",
                "verbose_name_plural": "RECICLAQUI",
            },
        ),
        migrations.CreateModel(
            name="todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=255)),
                ("status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criacao", models.DateTimeField(auto_created=True)),
                ("atualizacao", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("comentario", models.TextField(blank=True, default="")),
                ("avaliacao", models.DecimalField(decimal_places=1, max_digits=2)),
                (
                    "RECICLAQUI",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="core.reciclaquiapp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
                "unique_together": {("email", "RECICLAQUI")},
            },
        ),
    ]
